---
# Grab logs from all servers
- hosts: all
  # Limit number of hosts to run on simultaneously
  serial: 4

  # Playbook vars, which can be overridden through a custom `config/config.yml` file
  # or through the command-line (e.g. `ansible-playbook -e diag_path=$HOME`)
  vars:

    # Name of the sosreport executable
    - sosreport_args: '--compression-type=gzip --report --alloptions'

    # Name of the sosreport executable
    - sosreport_cmd: sosreport

    # Default path to put the collected diags (can override from command-line)
    - diag_path: diags

    # Name of the collected diag files
    - diag_filename: diag.tar.gz

    # Remote tmp directory to create diag files in (will be deleted, recreated - so be careful)
    - tmpdir: /var/tmp/sos-ansible

  tasks:

    - include: tasks/install.yml
      sudo: yes  
  
    - include: tasks/run.yml
      sudo: yes  
  
    - include: tasks/fetch.yml
      sudo: yes  
  
    - include: tasks/untar.yml
