#installs the relevant modules for the 3g
---
- name: Installs ppp
  apt: pkg=ppp state=present
  sudo: yes

- name: Configure ppp options for ZTE USB modem
  copy: src=../files/etc/ppp/options.mobile dest=/etc/ppp/options.mobile
  sudo: yes

- name: Configure ppp options for airtel provider
  copy: src=../files/etc/ppp/peers/airtel dest=/etc/ppp/peers/airtel
  sudo: yes
