---
- name: Check permissions
  action: acl name=/etc/ppp/options.mobile
  register: acl_info

- name: Checks ppp interface
  action: interfaces name=ppp0 iface_type=ppp provider=airtel

- name: Checks ppp service
  action: service name=pppd state=running enabled=yes
  
- name: Get ppp log
  action: fetch src=/var/log/upstart/networking.log dest=reports/

- name: Get ppp connect error log
  action: fetch src=/var/log/ppp-connect-errors dest=reports/
