#routing script which chooses the yml file based on tags
---
- include: report.yml tags=report,diagnose

- include: diagnose.yml tags=diagnose

- include: deploy.yml tags=deploy

- include: repair.yml tags=repair

- include: update.yml tags=update

- include: remove.yml tags=remove