#everything not installed with docker
---

## Systemd

- name: Install Systemd for managing docker and job scheduling
  apt: pkg=systemd state=present
  sudo: yes

- name: Install systemd in Grub
  replace: dest=/etc/default/grub regexp='^GRUB_CMDLINE_LINUX=""$' replace='GRUB_CMDLINE_LINUX="init=/bin/systemd"'
  register: updated_grub
  sudo: yes

- name: Update grub 
  command: update-grub
  when: updated_grub.changed
  sudo: yes

- name: Restart the server after update grub 
  command: "shutdown -r now"
  when: updated_grub.changed
  sudo: yes

#- name: Wait until the virtual machine stop ie. ssh port stop responding
#  local_action: wait_for host={{ansible_ssh_host}} port={{ansible_ssh_port}} state=stopped
#  sudo: false

- name: Wait for server to come up after update grub 
  local_action: wait_for host={{ansible_ssh_host}} port={{ansible_ssh_port}} delay=30
  when: updated_grub.changed
  sudo: false

- name: Install vim
  apt: pkg=vim state=present
  sudo: yes

- name: Install screen
  apt: pkg=screen state=present
  sudo: yes

- name: Default .screenrc
  copy: src=files/home/lastmile/.screenrc dest=/home/{{ansible_ssh_user}}/.screenrc owner={{ansible_ssh_user}} group={{ansible_ssh_user}} backup=yes
  sudo: yes

- name: Default .bash_profile starting screen
  copy: src=files/home/lastmile/.bash_profile dest=/home/{{ansible_ssh_user}}/.bash_profile owner={{ansible_ssh_user}} group={{ansible_ssh_user}} backup=yes
  sudo: yes

- name: Create ~/.ssh dir
  file: path=/home/{{ansible_ssh_user}}/.ssh state=directory
  sudo: yes

- name: Install git
  apt: pkg=git state=present
  sudo: yes

- name: Add github.com to known_hosts file
  copy: src=files/.ssh/known_hosts dest=/home/{{ansible_ssh_user}}/.ssh/known_hosts owner={{ansible_ssh_user}} group={{ansible_ssh_user}} mode=600 backup=yes
  sudo: yes
