---
- name: Installs uucp
  apt: pkg=uucp state=present
  sudo: yes

#write the uucp config
#- name: View all clinic systems
#  debug: item
#  with_items: ${groups.node}
#  sudo: yes

#fatal: [katombo] => with_items expects a list or a set
#  with_items:
#  - testuser1
#  - testuser2

#- name: Install systems in call file
#  lineinfile: dest=/etc/uucp/call line="{{ item }}\tU{{ item }}\t{{ item }}"
#  with_items: ${groups.node}
#  sudo: yes

#- name: Install prod-tcp system in call file
#  lineinfile: dest=/etc/uucp/call line="prod-tcp\tUprod\teeKaecaiw0"  
#  sudo: yes
