---
- name: Get uucp configuration
  synchronize: src=/etc/uucp dest={{ report_directory }}/{{ ansible_hostname }}/etc/uucp mode=pull rsync_path="sudo rsync"
  sudo: yes
  ignore_errors: yes

- name: Get uucp log
  synchronize: src=/var/log/uucp dest={{ report_directory }}/{{ ansible_hostname }}/var/log/uucp mode=pull rsync_path="sudo rsync"
  sudo: yes
  ignore_errors: yes

- name: Create uucp output directory
  command: mkdir /tmp/uucp-output creates=/tmp/uucp-output
  ignore_errors: yes
  

- name: Get uuchk results
  shell: uuchk > /tmp/uucp-output/uuchk.log
  sudo: yes
  ignore_errors: yes
  

- name: Get uustat -a check results
  shell: uustat -a > /tmp/uucp-output/uustat-a.log
  sudo: yes
  ignore_errors: yes
  

- name: Get uustat -p check results
  shell: uustat -p > /tmp/uucp-output/uustat-p.log
  sudo: yes
  ignore_errors: yes
  

- name: Get uucp output directory
  synchronize: src=/tmp/uucp-output dest={{ report_directory }}/{{ ansible_hostname }}/output/uucp mode=pull rsync_path="sudo rsync"
  ignore_errors: yes
  

- name: Remove uucp output directory
  command: rm -rf /tmp/uucp-output removes=/tmp/uucp-output
  ignore_errors: yes
  
