# Component needed to inform about the status of the box
---

- name: Install sensord
  apt: pkg=sensord state=present
  sudo: yes

- name: Installs lm-sensors
  apt: pkg=lm-sensors state=present
  sudo: yes

- name: Installs collectd-utils
  apt: pkg=collectd-utils state=present
  sudo: yes

- name: Install collectd config
  copy: src=files/etc/collectd/collectd.conf dest=/etc/collectd/collectd.conf  mode=755
  sudo: yes
  tags: status
  tags: 
    - 050to051

- name: Create status.sh directory
  file: path=/opt/ltfhc-status state=directory
  sudo: yes
  tags: status
  tags: 
    - 050to051
    - 040to051

- name: Install status.sh script
  copy: src=files/opt/ltfhc-status/status.sh dest=/opt/ltfhc-status/status.sh mode=755
  sudo: yes
  tags: status
  tags: 
    - 050to051
    - 040to051

- name: Install and customise status cron job
  template: src=files/etc/cron.d/status.template dest=/etc/cron.d/status
  sudo: yes
  tags: status
  tags: 
    - 050to051
    - 040to051

