---


- name: Add backports for node.js
  apt_repository: repo='deb http://ftp.us.debian.org/debian wheezy-backports main' state=present
  sudo: yes

- name: Install curl
  apt: pkg=curl state=present update_cache=true
  sudo: yes

- name: Install node.js
  apt: pkg=nodejs state=present update_cache=true
  sudo: yes

- name: Install nodejs-legacy (needed to run node as an executable)
  apt: pkg=nodejs-legacy state=present
  sudo: yes

- name: Install npm
  shell: '/usr/bin/curl --insecure https://www.npmjs.org/install.sh | /bin/bash creates=/usr/bin/npm'
  sudo: yes

- name: Install kanso
  command: npm install -g kanso creates=/usr/bin/kanso
  sudo: yes

- name: Patch Kanso to allow pushing to self-signed certificate https
  lineinfile: 'dest=/usr/lib/node_modules/kanso/lib/couchdb.js regexp="        rejectUnauthorized: ''false''," insertafter="var request = proto.request" line="        rejectUnauthorized: ''false'',"'
  sudo: yes

- name: Clone emr application
  git: repo=https://github.com/iilab/ltfhc-next.git dest=/opt/ltfhc-next
  sudo: yes

- name: Copy ltfhc-next files 
  synchronize: src=../../ltfhc-next dest=/opt/ltfhc-next/
  sudo: yes
#  tags: 050to051

- name: Install and customise .kansorc
  template: src=files/.kansorc.template dest=/opt/ltfhc-next/.kansorc
  sudo: yes
  tags: 050to051

- name: Install and customise kanso.json
  template: src=files/kanso.json.template dest=/opt/ltfhc-next/kanso.json
  sudo: yes
  tags: 050to051

- name: Push emr application
  command: kanso push chdir=/opt/ltfhc-next
  sudo: yes
#  tags: 050to051
