---
- name: Create uname output directory
  command: mkdir /tmp/uname-output creates=/tmp/uname-output

- name: Get uname -a results
  shell: uname -a > /tmp/uname-output/uname-a.log
  sudo: yes

- name: Get apt output directory
  synchronize: src=/tmp/uname-output dest={{ report_directory }}/{{ inventory_hostname }}/output/uname mode=pull rsync_path="sudo rsync"

- name: Remove uname output directory
  command: rm -rf /tmp/uname-output removes=/tmp/uname-output