---
- name: Get apt configuration
  synchronize: src=/etc/apt dest={{ report_directory }}/{{ inventory_hostname }}/etc/apt mode=pull rsync_path="sudo rsync"
  sudo: yes

- name: Get apt log
  synchronize: src=/var/log/apt dest={{ report_directory }}/{{ inventory_hostname }}/var/log/apt mode=pull rsync_path="sudo rsync"
  sudo: yes

- name: Create apt output directory
  command: mkdir /tmp/apt-output creates=/tmp/apt-output

- name: Get apt-get check results
  shell: apt-get check > /tmp/apt-output/apt-get_check.log
  sudo: yes

- name: Get apt-config dump results
  shell: apt-config dump > /tmp/apt-output/apt-config_dump.log
  sudo: yes

- name: Get apt-cache stats results
  shell: apt-cache stats > /tmp/apt-output/apt-cache_stats.log
  sudo: yes

- name: Get apt-cache policy results
  shell: apt-cache policy > /tmp/apt-output/apt-cache_policy.log
  sudo: yes

- name: Get apt output directory
  synchronize: src=/tmp/apt-output dest={{ report_directory }}/{{ inventory_hostname }}/output/apt mode=pull rsync_path="sudo rsync"

- name: Remove apt output directory
  command: rm -rf /tmp/apt-output removes=/tmp/apt-output