---

- name: reload systemctl
  command: systemctl --system daemon-reload
  sudo: yes
  tags: 
   - couchconfig
   - portal
   - 050to051

- name: restart ltfhc-couch
  service: name=ltfhc-couch.service enabled=yes state=restarted
  sudo: yes
  tags: 
    - couchconfig
    - couchdb
    - 050to051

- name: Restart couchdb service for Tanzania
  service: name=couchdb enabled=yes state=restarted
  sudo: yes
  tags: 
    - couchconfig
    - couchdb

- name: restart ltfhc-portal
  service: name=ltfhc-portal.service enabled=yes state=stopped
  sudo: yes
  tags: portal
