# Wireless Client mode: When the server needs to connect to an existing wireless access point.
# Wireless Access Point mode: When the server is deployed.
---
- include: report.yml tags=report

- include: diagnose.yml tags=diagnose

- include: deploy.yml tags=deploy,network

- include: mode_wirelessclient.yml tags=mode_wirelessclient

- include: mode_wirelessap.yml tags=mode_wirelessap

- include: remove.yml tags=remove
