---

- name: Install hostapd.conf
  copy: src=files/etc/hostapd/hostapd.conf dest=/etc/hostapd/hostapd.conf
  sudo: yes

- name: Install /etc/default/hostapd
  copy: src=files/etc/default/hostapd dest=/etc/default/hostapd
  sudo: yes

- name: Install /etc/dnsmasq.conf
  copy: src=files/etc/dnsmasq.conf dest=/etc/dnsmasq.conf
  sudo: yes

- name: Install /etc/network/interfaces for access point mode
  copy: src=files/etc/network/interfaces.ap dest=/etc/network/interfaces
  sudo: yes

- name: Install hostapd.service
  copy: src=files/etc/systemd/system/hostapd.service dest=/etc/systemd/system/hostapd.service
  sudo: yes

- name: Reload service file
  command: systemctl --system daemon-reload
  sudo: yes

- name: Restart networking.service
  service: name=networking enabled=yes state=restarted
  sudo: yes

# iptables -A FORWARD -o eth1 -i br0 -s 192.168.42.0/24 -m conntrack --ctstate NEW -j ACCEPT
# iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
# iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
# iptables -A FORWARD -o eth1 -s 192.168.1.0/16 -m conntrack --ctstate NEW -j ACCEPT

- name: Restart dnsmasq.service
  service: name=dnsmasq.service enabled=yes state=restarted
  sudo: yes

- name: Restart hostapd.service
  service: name=hostapd.service enabled=yes state=restarted
  sudo: yes

