---

- name: Install hostapd.conf
  copy: src=files/etc/hostapd/hostapd.conf dest=/etc/hostapd/hostapd.conf
  sudo: yes
  notify: 
   - reload systemctl
   - restart hostapd

- name: Install /etc/default/hostapd
  copy: src=files/etc/default/hostapd dest=/etc/default/hostapd
  sudo: yes
  notify: 
   - reload systemctl
   - restart hostapd

- name: Install /etc/dnsmasq.conf
  copy: src=files/etc/dnsmasq.conf dest=/etc/dnsmasq.conf
  sudo: yes
  notify: 
   - reload systemctl
   - restart dnsmasq

- name: Install /etc/network/interfaces.ap for access point mode
  copy: src=files/etc/network/interfaces.ap dest=/etc/network/interfaces
  sudo: yes
  notify: 
   - reload systemctl
   - restart networking

- name: Install hostapd.service
  copy: src=files/etc/systemd/system/hostapd.service dest=/etc/systemd/system/hostapd.service
  sudo: yes
  notify: 
   - reload systemctl
   - restart hostapd